apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-voice-caddy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-voice
  template:
    metadata:
      labels:
        app: open-voice
    spec:
      containers:
        - name: caddy
          image: caddy:latest
          ports:
            - containerPort: 8585
          volumeMounts:
            - name: open-voice-caddy-config
              mountPath: /etc/caddy/Caddyfile
              subPath: Caddyfile
      volumes:
        - name: open-voice-caddy-config
          configMap:
            name: open-voice-caddy-config
---
apiVersion: v1
kind: Service
metadata:
  name: open-voice-caddy-service
spec:
  type: LoadBalancer
  selector:
    app: open-voice
  ports:
    - name: open-voice-http
      protocol: TCP
      port: 8585
      targetPort: 8585